#!/usr/bin/env bash
# copy files from client to server (between two remote servers)

if [ $# -eq 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/ 
else
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY" 
fi
