#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" indefinitely.
#+ in between each iteration of the loop, add a sleep 2.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
