#!/usr/bin/env bash
# A Bash script that displays time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

china="bad luck from China"
japan="bad luck from Japan"
italy="bad luck from Italy"
i=0
j=1

while [ $i -lt 13 ];
do
	echo "Hour: $i"
	while [ $j -lt 60 ];
	do
		echo $j
		(( j++ ))
	done
	j=1
	(( i++ ))
done
