#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

var=`echo $(ls)` 

for el in $var;
do
	echo $el | cut -d "-" -f2
done
