#!/usr/bin/env bash
# Bash script that gives information about the "school" file

file=school

if [ -e "$file" ];
then
	echo "$file file exists"
	if [ -s "$file" ];
	then
		echo "$file is not empty"
	else
		echo "$file is empty"
	fi

	if [ -f "$file" ];
	then
		echo "$file is a regular file"
	fi
else
	echo "$file file doesn't exist"
fi
