#!/usr/bin/env bash
# Bash script that gives information about the "school" file

if [ -e "school" ];
then
	echo "school file exists"
	if [ -s "school" ];
	then
		echo "school is not empty"
	else
		echo "school is empty"
	fi

	if [ -f "school" ];
	then
		echo "school is a regular file"
	fi
else
	echo "school file doesn't exist"
fi
